version: 2

jobs:
  # Check code (UnitTest, Lint)
  check_code:
    docker:
      - image: circleci/node:12.7.0
    steps:
      # @see https://circleci.com/docs/2.0/caching/#source-caching
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      - checkout
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - .git

      # @see https://circleci.com/docs/2.0/caching/#npm-node
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run: npm install
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run:
          name: lint
          command: |
            npm run lint-dry
      - run:
          name: test
          command: |
            npm run test

workflows:
  version: 2
  feature-ci:
    jobs:
      - check_code:
          filters:
            branches:
              only:
                - /feature\/.*/
                - /renovate\/.*/
